apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.label }}-svc
  labels:
    app:  {{ .Values.label }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    version: {{ .Values.label1.version }}
    app: {{ .Values.label2.app }}