apiVersion: apps/v1
  2 kind: Deployment
  3 metadata:
  4   name: postgres-backup
  5 spec:
  6   replicas: 1
  7   selector:
  8     matchLabels:
  9       app: postgres-backup
 10   template:
 11     metadata:
 12       labels:
 13         app: postgres-backup
 14     spec:
 15       containers:
 16       - name: postgres-backup
 17         image: attamegnon/attamegnon2022:backup
 18         envFrom:
 19         - configMapRef:
 20             name: postgres-config
 21         - secretRef:
 22             name: aws-secret
 23        imagePullPolicy: Always
 24 
 25 ---
 26 apiVersion: batch/v1beta1
 27 kind: CronJob
 28 metadata:
 29   name: postgres-backup-cronjob
 30 spec:
 31   schedule: "*/3 * * * *"
 32   jobTemplate:
 33     spec:
 34       template:
 35         spec:
 36           containers:
 37           - name: postgres-backup
 38             image: attamegnon/attamegnon2022:backup
 39             envFrom:
 40             - configMapRef:
 41                 name: postgres-config
 42             - secretRef:
 43                 name: aws-secret
 44           restartPolicy: OnFailure
 45             imagePullPolicy: Always

