apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QVJLU0VSLVhOSUVNVkVSS1Q=
  AWS_SECRET_ACCESS_KEY: ajRsZldKcG5Mdk1sREpRNFlpUVozNUVHTW5vTXhRRS9YR1c2ZEk=
  AWS_DEFAULT_REGION: dXMtZWFzdC0x

